// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace EVO.Repository.Models;

public partial class ApplicationVersionScript
{
    public Guid Id { get; set; }

    public string Database { get; set; }

    public string ScriptName { get; set; }

    public DateTime ExecutionDate { get; set; }

    public bool Success { get; set; }

    public bool Rollback { get; set; }

    public string ErrorMessage { get; set; }

    public int Sequence { get; set; }

    public Guid ApplicationVersionId { get; set; }

    [JsonIgnore]
    public virtual ApplicationVersion ApplicationVersion { get; set; }
}