// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace EVO.Repository.Models;

public partial class ApplicationVersionComponent
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Label { get; set; }

    public string Description { get; set; }

    public string Version { get; set; }

    public bool Running { get; set; }

    public Guid ApplicationVersionId { get; set; }

    [JsonIgnore]
    public virtual ApplicationVersion ApplicationVersion { get; set; }
}