// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace EVO.Repository.Models;

public partial class ApplicationVersion
{
    public Guid Id { get; set; }

    public string Version { get; set; }

    public DateTime DeploymentDateTime { get; set; }

    public string ReleaseNotes { get; set; }

    public string Author { get; set; }

    public string Repository { get; set; }

    [JsonIgnore]
    public virtual ICollection<ApplicationVersionComponent> ApplicationVersionComponent { get; set; } = new List<ApplicationVersionComponent>();

    [JsonIgnore]
    public virtual ICollection<ApplicationVersionLabel> ApplicationVersionLabel { get; set; } = new List<ApplicationVersionLabel>();
    
    [JsonIgnore]
    public virtual ICollection<ApplicationVersionScript> ApplicationVersionScript { get; set; } = new List<ApplicationVersionScript>();
}