// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVO.Repository.Models;

public partial class User
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public int AccessLevelId { get; set; }

    public byte[] PasswordHash { get; set; }

    public byte[] PasswordSalt { get; set; }

    public DateTime RegisterDate { get; set; }

    public DateTime LastUpdate { get; set; }

    public bool CompleteRegistration { get; set; }

    public bool Active { get; set; }

    public virtual UserAccessLevelDomain AccessLevel { get; set; }

    public virtual ICollection<Customer> Customer { get; set; } = new List<Customer>();

    public virtual ICollection<InvoiceServices> InvoiceServicesApprovedByUserNavigation { get; set; } = new List<InvoiceServices>();

    public virtual ICollection<InvoiceServices> InvoiceServicesCreatedByUserNavigation { get; set; } = new List<InvoiceServices>();

    public virtual ICollection<ServiceByInvoice> ServiceByInvoice { get; set; } = new List<ServiceByInvoice>();
}