// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVO.Repository.Models;

public partial class UserAccessLevelDomain
{
    public int Id { get; set; }

    public string Function { get; set; }

    public string Department { get; set; }

    public string Description { get; set; }

    public virtual ICollection<User> User { get; set; } = new List<User>();
}